"""Generate and atomically write baked PS1 animation C files."""

import os
from pathlib import Path

from .animation_model import (
    BakedMeshAnimation,
    flatten_vertex_frames,
    resolve_animation_output_bases,
)
from .c_writer import (
    _restore_bytes,
    _stage_text,
    generate_triangle_array,
    generate_uv_array,
    make_include_guard,
)


def generate_animation_header(symbol_base: str) -> str:
    """Generate declarations for one baked mesh animation."""

    guard = make_include_guard(symbol_base)
    return (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        "#include <stdint.h>\n"
        "#include <psxgte.h>\n\n"
        "/* Generated by PSX Toolkit. */\n\n"
        "#ifndef PSX_TOOLKIT_MODEL_TYPES_DEFINED\n"
        "#define PSX_TOOLKIT_MODEL_TYPES_DEFINED\n\n"
        "typedef struct {\n"
        "    uint8_t u;\n"
        "    uint8_t v;\n"
        "} PSXUV;\n\n"
        "typedef struct {\n"
        "    uint16_t vertex[3];\n"
        "    uint16_t uv[3];\n"
        "} PSXTriangle;\n\n"
        "#endif\n\n"
        f"extern const SVECTOR {symbol_base}_frames[];\n"
        f"extern const int32_t {symbol_base}_source_frames[];\n"
        f"extern const PSXUV {symbol_base}_uvs[];\n"
        f"extern const PSXTriangle {symbol_base}_triangles[];\n\n"
        f"extern const uint16_t {symbol_base}_frame_count;\n"
        f"extern const uint16_t {symbol_base}_vertex_count;\n"
        f"extern const uint16_t {symbol_base}_uv_count;\n"
        f"extern const uint16_t {symbol_base}_triangle_count;\n\n"
        f"/* Frame offset = frame_index * {symbol_base}_vertex_count. */\n\n"
        "#endif\n"
    )


def generate_animation_vertex_array(
    symbol_base: str,
    animation: BakedMeshAnimation,
) -> str:
    """Format frame-major vertices as one flat contiguous SVECTOR array."""

    lines = [f"const SVECTOR {symbol_base}_frames[] = {{"]
    flattened = flatten_vertex_frames(animation.vertex_frames)
    vertex_count = animation.vertex_count
    for frame_index, source_frame in enumerate(animation.source_frames):
        lines.append(f"    /* Source frame {source_frame} */")
        start = frame_index * vertex_count
        for vertex in flattened[start : start + vertex_count]:
            lines.append(f"    {{ {vertex.x}, {vertex.y}, {vertex.z}, 0 }},")
    lines.append("};")
    return "\n".join(lines)


def generate_source_frame_array(
    symbol_base: str,
    source_frames: tuple[int, ...],
) -> str:
    """Format sampled Blender timeline frame numbers."""

    lines = [f"const int32_t {symbol_base}_source_frames[] = {{"]
    lines.extend(f"    {frame}," for frame in source_frames)
    lines.append("};")
    return "\n".join(lines)


def generate_animation_source(
    symbol_base: str,
    animation: BakedMeshAnimation,
) -> str:
    """Generate definitions for one baked mesh animation."""

    return (
        f'#include "{symbol_base}.h"\n\n'
        "/* Generated by PSX Toolkit. */\n\n"
        f"{generate_animation_vertex_array(symbol_base, animation)}\n\n"
        f"{generate_source_frame_array(symbol_base, animation.source_frames)}\n\n"
        f"{generate_uv_array(symbol_base, animation.uvs)}\n\n"
        f"{generate_triangle_array(symbol_base, animation.triangles)}\n\n"
        f"const uint16_t {symbol_base}_frame_count = {animation.frame_count};\n"
        f"const uint16_t {symbol_base}_vertex_count = {animation.vertex_count};\n"
        f"const uint16_t {symbol_base}_uv_count = {len(animation.uvs)};\n"
        f"const uint16_t {symbol_base}_triangle_count = "
        f"{len(animation.triangles)};\n"
    )


def animation_output_paths(
    directory: Path,
    animations: tuple[BakedMeshAnimation, ...],
    animation_name: str,
) -> tuple[Path, ...]:
    """Return every generated path, rejecting sanitized-name collisions."""

    symbol_bases = resolve_animation_output_bases(
        tuple(animation.mesh_name for animation in animations),
        animation_name,
    )
    paths = []
    for symbol_base in symbol_bases:
        paths.extend((directory / f"{symbol_base}.c", directory / f"{symbol_base}.h"))
    return tuple(paths)


def _generated_outputs(
    directory: Path,
    animations: tuple[BakedMeshAnimation, ...],
    animation_name: str,
) -> tuple[tuple[Path, str], ...]:
    paths = animation_output_paths(directory, animations, animation_name)
    symbol_bases = resolve_animation_output_bases(
        tuple(animation.mesh_name for animation in animations),
        animation_name,
    )
    outputs = []
    for index, (animation, symbol_base) in enumerate(
        zip(animations, symbol_bases, strict=True)
    ):
        source_path = paths[index * 2]
        header_path = paths[index * 2 + 1]
        outputs.extend(
            (
                (source_path, generate_animation_source(symbol_base, animation)),
                (header_path, generate_animation_header(symbol_base)),
            )
        )
    return tuple(outputs)


def write_animation_files(
    directory: Path,
    animations: tuple[BakedMeshAnimation, ...],
    animation_name: str,
    *,
    overwrite: bool = False,
) -> tuple[Path, ...]:
    """Generate, stage, and replace all per-mesh animation file pairs together."""

    if not directory.exists():
        raise FileNotFoundError(f"Output directory does not exist: {directory}")
    if not directory.is_dir():
        raise NotADirectoryError(f"Output path is not a directory: {directory}")

    outputs = _generated_outputs(directory, animations, animation_name)
    targets = tuple(path for path, _content in outputs)
    if not overwrite and any(path.exists() for path in targets):
        raise FileExistsError("One or more animation output files already exist.")

    original_contents = {
        target: target.read_bytes() if target.exists() else None for target in targets
    }
    staged_paths = []
    replaced_targets = []
    try:
        for target, content in outputs:
            staged_paths.append(_stage_text(target, content))
        for temporary_path, target in zip(staged_paths, targets, strict=True):
            os.replace(temporary_path, target)
            replaced_targets.append(target)
    except Exception:
        for target in reversed(replaced_targets):
            original_content = original_contents[target]
            if original_content is None:
                target.unlink(missing_ok=True)
            else:
                _restore_bytes(target, original_content)
        raise
    finally:
        for temporary_path in staged_paths:
            temporary_path.unlink(missing_ok=True)

    return targets
