"""Generate and write static PS1 C model files without Blender dependencies."""

import os
import tempfile
from pathlib import Path

from .model import ExportMesh, ExportTriangle, ExportUV, ExportVertex


def make_include_guard(symbol_base: str) -> str:
    """Return the include guard used by a generated model header."""

    return f"{symbol_base.upper()}_H"


def generate_header(symbol_base: str) -> str:
    """Generate declarations for one static PS1 model."""

    guard = make_include_guard(symbol_base)
    return (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        "#include <stdint.h>\n"
        "#include <psxgte.h>\n\n"
        "/* Generated by PSX Toolkit. */\n\n"
        "#ifndef PSX_TOOLKIT_MODEL_TYPES_DEFINED\n"
        "#define PSX_TOOLKIT_MODEL_TYPES_DEFINED\n\n"
        "typedef struct {\n"
        "    uint8_t u;\n"
        "    uint8_t v;\n"
        "} PSXUV;\n\n"
        "typedef struct {\n"
        "    uint16_t vertex[3];\n"
        "    uint16_t uv[3];\n"
        "} PSXTriangle;\n\n"
        "#endif\n\n"
        f"extern const SVECTOR {symbol_base}_vertices[];\n"
        f"extern const PSXUV {symbol_base}_uvs[];\n"
        f"extern const PSXTriangle {symbol_base}_triangles[];\n\n"
        f"extern const uint16_t {symbol_base}_vertex_count;\n"
        f"extern const uint16_t {symbol_base}_uv_count;\n"
        f"extern const uint16_t {symbol_base}_triangle_count;\n\n"
        "#endif\n"
    )


def generate_vertex_array(
    symbol_base: str,
    vertices: tuple[ExportVertex, ...],
) -> str:
    """Format an SVECTOR array."""

    lines = [f"const SVECTOR {symbol_base}_vertices[] = {{"]
    lines.extend(
        f"    {{ {vertex.x}, {vertex.y}, {vertex.z}, 0 }}," for vertex in vertices
    )
    lines.append("};")
    return "\n".join(lines)


def generate_uv_array(symbol_base: str, uvs: tuple[ExportUV, ...]) -> str:
    """Format an 8-bit UV array."""

    lines = [f"const PSXUV {symbol_base}_uvs[] = {{"]
    lines.extend(f"    {{ {uv.u}, {uv.v} }}," for uv in uvs)
    lines.append("};")
    return "\n".join(lines)


def generate_triangle_array(
    symbol_base: str,
    triangles: tuple[ExportTriangle, ...],
) -> str:
    """Format triangle vertex and corner-UV indices."""

    lines = [f"const PSXTriangle {symbol_base}_triangles[] = {{"]
    for triangle in triangles:
        vertex = ", ".join(str(index) for index in triangle.vertex)
        uv = ", ".join(str(index) for index in triangle.uv)
        lines.append(f"    {{ {{ {vertex} }}, {{ {uv} }} }},")
    lines.append("};")
    return "\n".join(lines)


def generate_source(symbol_base: str, mesh: ExportMesh) -> str:
    """Generate definitions for one static PS1 model."""

    return (
        f'#include "{symbol_base}.h"\n\n'
        "/* Generated by PSX Toolkit. */\n\n"
        f"{generate_vertex_array(symbol_base, mesh.vertices)}\n\n"
        f"{generate_uv_array(symbol_base, mesh.uvs)}\n\n"
        f"{generate_triangle_array(symbol_base, mesh.triangles)}\n\n"
        f"const uint16_t {symbol_base}_vertex_count = {len(mesh.vertices)};\n"
        f"const uint16_t {symbol_base}_uv_count = {len(mesh.uvs)};\n"
        f"const uint16_t {symbol_base}_triangle_count = {len(mesh.triangles)};\n"
    )


def _stage_text(target: Path, content: str) -> Path:
    """Write content beside its target and return the temporary path."""

    descriptor, temporary_name = tempfile.mkstemp(
        dir=target.parent,
        prefix=f".{target.name}.",
        suffix=".tmp",
        text=True,
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
    except Exception:
        Path(temporary_name).unlink(missing_ok=True)
        raise
    return Path(temporary_name)


def _restore_bytes(target: Path, content: bytes) -> None:
    """Atomically restore original target bytes after a failed paired write."""

    descriptor, temporary_name = tempfile.mkstemp(
        dir=target.parent,
        prefix=f".{target.name}.",
        suffix=".restore",
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
        os.replace(temporary_path, target)
    finally:
        temporary_path.unlink(missing_ok=True)


def write_model_files(
    directory: Path,
    symbol_base: str,
    mesh: ExportMesh,
    *,
    overwrite: bool = False,
) -> tuple[Path, Path]:
    """Stage and replace a matching static model source/header pair."""

    source_path = directory / f"{symbol_base}.c"
    header_path = directory / f"{symbol_base}.h"
    targets = (source_path, header_path)

    if not directory.exists():
        raise FileNotFoundError(f"Output directory does not exist: {directory}")
    if not directory.is_dir():
        raise NotADirectoryError(f"Output path is not a directory: {directory}")
    if not overwrite and any(path.exists() for path in targets):
        raise FileExistsError("One or both output files already exist.")

    contents = (generate_source(symbol_base, mesh), generate_header(symbol_base))
    original_contents = {
        target: target.read_bytes() if target.exists() else None for target in targets
    }
    staged_paths: list[Path] = []
    replaced_targets: list[Path] = []
    try:
        for target, content in zip(targets, contents, strict=True):
            staged_paths.append(_stage_text(target, content))
        for temporary_path, target in zip(staged_paths, targets, strict=True):
            os.replace(temporary_path, target)
            replaced_targets.append(target)
    except Exception:
        for target in reversed(replaced_targets):
            original_content = original_contents[target]
            if original_content is None:
                target.unlink(missing_ok=True)
            else:
                _restore_bytes(target, original_content)
        raise
    finally:
        for temporary_path in staged_paths:
            temporary_path.unlink(missing_ok=True)

    return source_path, header_path
